### ISSUE TITLE
No data being returned, limited API.

### ISSUE THREAD

**Issue by bmclain** [celpax/dailypulse#1]
Calling MoodKPI and PulsesPerTypicalDay returns the following:

{ pulses: null, date: '2016-08-03' }
{ red: null, green: null, date: '2016-08-03' }

Even though there were 30 pulses so far this week.

Also, is there any way to get access to the full API? We want to pull this data to be included in a larger dashboard in our existing business intelligence platform.

**Comment by rvalle** [comment]
Hi, 

My guess is that you still don't have a mood KPI. How long has your celpax been deployed? 

It takes 30 days of data,  check in your dashboard to ensure you have a Mood KPI. 

We are reviewing the API for additional functionality. Could you send your API  requirements to support@celpax.com? Please include information about your BI dashboard also. That way we will ensure that we cover your requirements on future releases.
